# sample netlify.toml
[build]
  command = "yarn run build"
  functions = "functions" # netlify dev uses this directory to scaffold and serve your functions
  publish = "dist"

# note: each of these fields are OPTIONAL
[dev]
  command = "yarn start" # Command to start your dev server
  targetPort = 5173
  autoLaunch = true
